logging:
  level:
    ROOT: DEBUG
    io.github.jhipster: DEBUG
    og.aust.admission: DEBUG

spring:
  profiles:
    active: dev
#    include:
#      - swagger
      # Uncomment to activate TLS for the dev profile
      #- tls
  devtools:
    restart:
      enabled: true
      additional-exclude: static/**
    livereload:
      enabled: false # we use Webpack dev server + BrowserSync for livereload
  jackson:
    serialization:
      indent-output: true
#  mail:
#    host: localhost
#    port: 25
#    username:
#    password:
  messages:
    cache-duration: PT1S # 1 second, see the ISO 8601 standard
  thymeleaf:
    cache: false
  sleuth:
    sampler:
      probability: 1 # report 100% of traces
  zipkin: # Use the "zipkin" Maven profile to have the Spring Cloud Zipkin dependencies
    base-url: http://localhost:9411
    enabled: false
    locator:
      discovery:
        enabled: true


server:
  port: 8080
  forward-headers-strategy: native
